#!/usr/bin/env python3
from dis import dis
from tkinter import DISABLED
import vdf
import os
import toml
from sys import platform
from divamod import DivaMod, UnmanageableModError
import colorama
from manage import load_mods
from simple_term_menu import TerminalMenu

MEGAMIX_APPID = 1761390
LIBRARYFOLDERS_VDF_PATH = os.path.expanduser("~/.local/share/Steam/config/libraryfolders.vdf")

if platform != "linux":
    print("this mod manager is only supported on linux")
    quit()

if not os.path.isfile(LIBRARYFOLDERS_VDF_PATH):
    print("cannot find libraryfolders.vdf")

MEGAMIX_PATH = None

with open(LIBRARYFOLDERS_VDF_PATH) as vdf_fd:
    data = vdf.parse(vdf_fd)
    for library_index in data["libraryfolders"]:
        library_folder = data["libraryfolders"][library_index]
        if str(MEGAMIX_APPID) in library_folder["apps"] and MEGAMIX_PATH == None:
            MEGAMIX_PATH = os.path.join(library_folder['path'], "steamapps/common/Hatsune Miku Project DIVA Mega Mix Plus/")

if MEGAMIX_PATH == None:
    print("couldn't find megamix install directory, is it installed?")
    quit()

if not os.path.isfile(os.path.join(MEGAMIX_PATH, "config.toml")):
    print("couldn't find config.toml in megamix root, is DivaModLoader installed?")
    quit()

with open(os.path.join(MEGAMIX_PATH, "config.toml")) as conf_fd:
    config = toml.load(conf_fd)
    ENABLED_MODS_PATH = MEGAMIX_PATH + config["mods"]
    DISABLED_MODS_PATH = MEGAMIX_PATH + config.get("disabled_mods", "disabled_mods")

for d in [ENABLED_MODS_PATH, DISABLED_MODS_PATH]:
    os.makedirs(d, exist_ok=True)

enabled_mods, unmanageable_mods = load_mods(ENABLED_MODS_PATH)
disabled_mods, unmanageable_mods_2 = load_mods(DISABLED_MODS_PATH)

options = ["Install new mods", "Manage existing mods", "Exit"]
print("d4m v0.0")
manageable = len(enabled_mods) + len(disabled_mods)
unmanageable = len(unmanageable_mods) + len(unmanageable_mods_2)
print(f"{manageable+unmanageable} installed")
while True:
    root_menu = TerminalMenu(options)
    sel = root_menu.show()
    if sel == 0: #isntall new
        pass
    elif sel ==1: #manage existing
        pass
    else:
        break